/**
 * Ship geometry types.
 * Auto-generated by scripts/build/bundle-meshes.mjs - do not edit manually.
 */

/** Valid ship class names (generated from GLB filenames) */
export type ShipClass =
  | 'bomber'
  | 'defender'
  | 'fighter'
  | 'interceptor'
  | 'military'
  | 'mining'
  | 'patrol'
  | 'raider'
  | 'refinery'
  | 'scout'
  | 'sentinel'
  | 'striker'
  | 'transport'
  | 'waypoint';

/** Mesh bounding box (X and Z extents for hardpoint mapping) */
export interface MeshBounds {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
}

/** SVG content bounding box (actual ship silhouette within 64x64 viewBox) */
export interface SvgBounds {
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
}

/**
 * A plane in the convex hull (normal + distance from origin).
 *
 * Note: This type is intentionally duplicated from hull-collider.ts to avoid
 * circular dependencies (ship-geometries.ts is imported by rendering code,
 * hull-collider.ts is imported by ECS code). Both definitions are identical.
 */
export interface HullPlane {
  nx: number;
  ny: number;
  nz: number;
  d: number;
}

/** Sub-hull for compound collision (connected components) */
export interface SubHull {
  planes: HullPlane[];
  boundingRadius: number;
}

/** Raw geometry data for a ship mesh */
export interface ShipGeometryData {
  positions: number[];
  normals: number[] | null;
  indices: number[] | null;
  bounds: MeshBounds;
  svgBounds: SvgBounds | null;
  /** Convex hull face planes for collision detection */
  hull: HullPlane[] | null;
  /** Volume of convex hull (for mass derivation) */
  hullVolume: number;
  /** Bounding radius of hull (for fast early-out checks) */
  hullBoundingRadius: number;
  /** Sub-hulls for compound collision (structures with disconnected parts) */
  subHulls: SubHull[] | null;
}
