/**
 * Embedded ship geometry data.
 * Auto-generated by scripts/build/bundle-meshes.mjs - do not edit manually.
 *
 * This file re-exports from split modules for backwards compatibility.
 * The actual data is split into separate chunks for better loading:
 * - ship-geometry-ships.ts: Combat ship geometries
 * - ship-geometry-structures.ts: Station/structure geometries
 */

// Re-export types
export type {
  HullPlane,
  MeshBounds,
  ShipClass,
  ShipGeometryData,
  SubHull,
  SvgBounds,
} from './ship-geometry-types';

// Import data from split modules
import { SHIP_GEOMETRY_SHIPS } from './ship-geometry-ships';
import { SHIP_GEOMETRY_STRUCTURES } from './ship-geometry-structures';
import type { ShipClass, ShipGeometryData } from './ship-geometry-types';

/** Combined geometry data for all ship classes */
export const SHIP_GEOMETRIES: Record<ShipClass, ShipGeometryData> = {
  ...SHIP_GEOMETRY_SHIPS,
  ...SHIP_GEOMETRY_STRUCTURES,
} as Record<ShipClass, ShipGeometryData>;
